kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "keycloak-react-auth.fullname" . }}
  labels:
{{- include "keycloak-react-auth.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClass }}
  volumeMode: {{ .Values.pvc.volumeMode }}