apiVersion: v1
data:
  config-keycloak-react-auth.json: |-
    {
      "APP_PORT": 4926,
      "SOCKET_PORT": 6011,
      "deploymentName": "acoustic-keycloak-react",
      "imageName": "acoustic-keycloak-react:latest",
      "namespaceStr": "acoustics",
      "cmNameStr": "dc-demo",
      "cmNameKeyStr": "test.json",
      "APPHOST_ENDPOINT": "keycloak-react-auth-acous-proj-01-dev.apps.9.178.216.70.nip.io",
      "BISERVER_ENDPOINT": "keycloak-react-auth-acous-proj-01-dev.apps.9.178.216.70.nip.io",
      "WEBSOCKET_ENDPOINT": "keycloak-react-auth-ws-acous-proj-01-dev.apps.9.178.216.70.nip.io",
      "_WEBSOCKET_ENDPOINT": "9.194.174.78:6011/",
      "DISCOVERY_URL": "https://api.us-south.discovery.watson.cloud.ibm.com/instances/0c92feaf-df9a-4bf9-ace3-c3c4b04b9067",
      "DISCOVERY_SERVICEURL": "https://api.us-south.discovery.watson.cloud.ibm.com",
      "DISCOVERY_APIKEY": "2JUGDzP1UYvIB5mxGg9LCrESakB1Nc3XieccV5Y9lk4e",
      "DISCOVERY_PROJECTID": "1605c87c-a724-4bf3-8ead-dd9df7671f62",
      "wsServer": "wss://audiostream-service-route-acoustics.9.178.216.51.nip.io",
      "wsPort": 443,
      "visualInferenceEndpoint": "https://9.178.216.86/visual-insights/api/dlapis/c1fd25db-f39f-4eb6-bda0-ad0e304da7c2",
      "classifyEndpoint": "https://smarto-python-instance-aa-instance-ibm-acous-proj-01-dev.apps.9.178.216.70.nip.io/classifyWAV",
      "_2classifyEndpoint": "https://smarto-python-instance-aa-instance-ibm-think2020.apps-crc.testing/classifyWAV",
      "_reyclassifyEndpoint": "http://acoustics-services-mfg-acous-proj-01-dev.apps.9.178.216.70.nip.io/api/v1/acoustics/classify_sounds/",
      "classifyUpload": "https://health-care-api-wise-hyena-wn.mybluemix.net/api/v1/users/87a21c73-1af4-4876-bfaf-a63943e6b4e8/cough",
      "sampleRate": 48000,
      "channelCount": 1,
      "bitDepth": 16,
      "volume": 1.0,
      "latency": 1,
      "noiseSuppression": false,
      "echoCancellation": false,
      "autoGainControl": false,
      "googAutoGainControl": false
    }
kind: ConfigMap
metadata:
  labels:
{{- include "keycloak-react-auth.labels" . | nindent 4 }}
  name: {{ include "keycloak-react-auth.fullname" . }}